"""create mbti tables

Revision ID: 08199a8c1470
Revises: 98b42ab4bb2b
Create Date: 2025-04-01 12:55:17.156277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08199a8c1470'
down_revision: Union[str, None] = '98b42ab4bb2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mbti_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('dimension', sa.String(length=10), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mbti_questions_id'), 'mbti_questions', ['id'], unique=False)
    op.create_table('mbti_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_code', sa.String(length=4), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_code')
    )
    op.create_index(op.f('ix_mbti_results_id'), 'mbti_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mbti_results_id'), table_name='mbti_results')
    op.drop_table('mbti_results')
    op.drop_index(op.f('ix_mbti_questions_id'), table_name='mbti_questions')
    op.drop_table('mbti_questions')
    # ### end Alembic commands ###
