"""refactor MBTIQuestion structure

Revision ID: 0ded5a8773e7
Revises: c61da662bff6
Create Date: 2025-04-10 19:37:44.949142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ded5a8773e7'
down_revision: Union[str, None] = 'c61da662bff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mbti_questions', sa.Column('trait_a', sa.String(length=1), nullable=False))
    op.add_column('mbti_questions', sa.Column('trait_b', sa.String(length=1), nullable=False))
    op.alter_column('mbti_questions', 'question_a',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('mbti_questions', 'question_b',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    op.drop_column('mbti_questions', 'dichotomy')
    op.drop_column('mbti_questions', 'text')
    op.drop_column('mbti_questions', 'trait')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mbti_questions', sa.Column('trait', sa.VARCHAR(length=1), autoincrement=False, nullable=False))
    op.add_column('mbti_questions', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('mbti_questions', sa.Column('dichotomy', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.alter_column('mbti_questions', 'question_b',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mbti_questions', 'question_a',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('mbti_questions', 'trait_b')
    op.drop_column('mbti_questions', 'trait_a')
    # ### end Alembic commands ###
