"""add Habit model and week_log

Revision ID: 5efe78d9a9b8
Revises: a12fc12ed04e
Create Date: 2025-04-15 10:54:37.304682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5efe78d9a9b8'
down_revision: Union[str, None] = 'a12fc12ed04e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_habits', sa.Column('week_log', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_habits', 'week_log')
    # ### end Alembic commands ###
