"""Rename archtype to archetype

Revision ID: 61d4cea01b98
Revises: 1b1e9029bf58
Create Date: 2025-04-14 14:40:14.098557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61d4cea01b98'
down_revision: Union[str, None] = '1b1e9029bf58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'archetype')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('archetype', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
