"""Add hero_step_progress and fix relationships

Revision ID: 65152c1eea77
Revises: a0c1ea2b905c
Create Date: 2025-04-10 13:55:27.538626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65152c1eea77'
down_revision: Union[str, None] = 'a0c1ea2b905c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'xp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('xp', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
