"""add test_type column to tests

Revision ID: 6b95a6bf80ad
Revises: aa0e10bd278a
Create Date: 2025-03-29 23:26:50.000783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b95a6bf80ad'
down_revision: Union[str, None] = 'aa0e10bd278a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mbti_questions')
    op.add_column('tests', sa.Column('test_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'test_type')
    op.create_table('mbti_questions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('dimension', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='mbti_questions_pkey')
    )
    # ### end Alembic commands ###
