"""add trait to mbti_questions

Revision ID: 8acc3f016745
Revises: 08199a8c1470
Create Date: 2025-04-01 13:16:54.833417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8acc3f016745'
down_revision: Union[str, None] = '08199a8c1470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mbti_questions', sa.Column('trait', sa.String(length=1), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mbti_questions', 'trait')
    # ### end Alembic commands ###
