"""add mbti_type to users

Revision ID: 98b42ab4bb2b
Revises: 2e37686cdf34
Create Date: 2025-03-30 01:15:28.603842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98b42ab4bb2b'
down_revision: Union[str, None] = '2e37686cdf34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mbti_results')
    op.drop_table('mbti_questions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mbti_questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('dimension', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='mbti_questions_pkey')
    )
    op.create_table('mbti_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type_code', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='mbti_results_pkey'),
    sa.UniqueConstraint('type_code', name='mbti_results_type_code_key')
    )
    # ### end Alembic commands ###
